name: build-test
# Run this any time there's a push, and allow this to be called from other workflows
on: [push, workflow_call]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]

    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - run: pnpm install

      - name: Dependencies audit
        run: pnpm audit --audit-level=moderate

      - name: Build
        run: pnpm run build

      - name: Format check
        run: pnpm run format:check

      - name: Lint check
        run: pnpm run lint:check

      - name: Spell check
        run: pnpm run spell:check

      - name: Test
        run: pnpm run test
